// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzujVPVXfvkY8NTr2Ju9tOjeyDdvv6BmM',
    appId: '1:270593032705:web:e5ebc199aa71a3230c3600',
    messagingSenderId: '270593032705',
    projectId: 'zuriel-5ef8b',
    authDomain: 'zuriel-5ef8b.firebaseapp.com',
    databaseURL: 'https://zuriel-5ef8b.firebaseio.com',
    storageBucket: 'zuriel-5ef8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3FRzW2_av4AdPnuz17OBIYaCida2x-E',
    appId: '1:270593032705:android:dc26713edab0dbba',
    messagingSenderId: '270593032705',
    projectId: 'zuriel-5ef8b',
    databaseURL: 'https://zuriel-5ef8b.firebaseio.com',
    storageBucket: 'zuriel-5ef8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRm2GT1dFjPeU6cmT2GuJGj4GFP8YjXk',
    appId: '1:270593032705:ios:0eb8cb25b3ada0290c3600',
    messagingSenderId: '270593032705',
    projectId: 'zuriel-5ef8b',
    databaseURL: 'https://zuriel-5ef8b.firebaseio.com',
    storageBucket: 'zuriel-5ef8b.appspot.com',
    androidClientId: '270593032705-ugivume8dibfgrhgo13f8jvdd1bei7tm.apps.googleusercontent.com',
    iosBundleId: 'com.christianappdevelopers.zuriel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkRm2GT1dFjPeU6cmT2GuJGj4GFP8YjXk',
    appId: '1:270593032705:ios:0eb8cb25b3ada0290c3600',
    messagingSenderId: '270593032705',
    projectId: 'zuriel-5ef8b',
    databaseURL: 'https://zuriel-5ef8b.firebaseio.com',
    storageBucket: 'zuriel-5ef8b.appspot.com',
    androidClientId: '270593032705-ugivume8dibfgrhgo13f8jvdd1bei7tm.apps.googleusercontent.com',
    iosBundleId: 'com.christianappdevelopers.zuriel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzujVPVXfvkY8NTr2Ju9tOjeyDdvv6BmM',
    appId: '1:270593032705:web:1090cbb02f9d0b190c3600',
    messagingSenderId: '270593032705',
    projectId: 'zuriel-5ef8b',
    authDomain: 'zuriel-5ef8b.firebaseapp.com',
    databaseURL: 'https://zuriel-5ef8b.firebaseio.com',
    storageBucket: 'zuriel-5ef8b.appspot.com',
  );

}