// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXi9WXVMmEKNqqqBO9Dq1C7h-RF6YGW1w',
    appId: '1:989624673159:web:ab73b177ac5eea95762922',
    messagingSenderId: '989624673159',
    projectId: 'zuriel-app',
    authDomain: 'zuriel-app.firebaseapp.com',
    databaseURL: 'https://zuriel-app-default-rtdb.firebaseio.com',
    storageBucket: 'zuriel-app.appspot.com',
    measurementId: 'G-NCE4JE2NHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvwVD3wxH_QhAQ10epPm0I87yPuOCy1k',
    appId: '1:989624673159:android:4cbab19b5a077eac762922',
    messagingSenderId: '989624673159',
    projectId: 'zuriel-app',
    databaseURL: 'https://zuriel-app-default-rtdb.firebaseio.com',
    storageBucket: 'zuriel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0IpX2cRRZK4iJT3meKyFhb6kOOzsu4E',
    appId: '1:989624673159:ios:a830762695bb416b762922',
    messagingSenderId: '989624673159',
    projectId: 'zuriel-app',
    databaseURL: 'https://zuriel-app-default-rtdb.firebaseio.com',
    storageBucket: 'zuriel-app.appspot.com',
    iosBundleId: 'com.christianappdevelopers.zuriel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA0IpX2cRRZK4iJT3meKyFhb6kOOzsu4E',
    appId: '1:989624673159:ios:a830762695bb416b762922',
    messagingSenderId: '989624673159',
    projectId: 'zuriel-app',
    databaseURL: 'https://zuriel-app-default-rtdb.firebaseio.com',
    storageBucket: 'zuriel-app.appspot.com',
    iosBundleId: 'com.christianappdevelopers.zuriel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXi9WXVMmEKNqqqBO9Dq1C7h-RF6YGW1w',
    appId: '1:989624673159:web:e0d7ef2dbc6bd8ff762922',
    messagingSenderId: '989624673159',
    projectId: 'zuriel-app',
    authDomain: 'zuriel-app.firebaseapp.com',
    databaseURL: 'https://zuriel-app-default-rtdb.firebaseio.com',
    storageBucket: 'zuriel-app.appspot.com',
    measurementId: 'G-PX77SZ7ELB',
  );
}
